### ISSUE TITLE
Can't update "Category" field of the selected rate 

### ISSUE THREAD

**Issue by marbanijessa** [AyannahQA/test#9]
The "Category" field of selected rate was not updated 

STEPS:
1. Click "SKUs"
2. Click "Edit" button of the selected rate
3. Edit "Category" field
4. Click "Update" button

DATA:
Account Used: 
 Username: test@test.com
 Password: 12345678
Selected Rate: 
Product: LOAD
**Category: GLOBE**
Sub Category: 
Name:  GoUnli
Description: Unlimited text and call to all networks
Sku: GU20
Type: default   
Charging type: FIX
Amount:  18.00
Facevalue: 20.00
Floor: 1.00       
Ceiling:  20.00    
Effectivity_date: 2017-12-28 18:18:00

Edit Category Field:
**Category Field: SUN**

ACTUAL RESULT:
(4) After Clicking "Update" button, message prompted.  
Confirmation message:
     "Rate updated"

However, the "Category" field of the selected rate was not updated

EXPECTED RESULT:
 The "Category" field of the rates should be updated.

**Comment by rpaningbatan** [comment]
issue fixed. category has been fixed and able to update.
